##### 1. Создайте одномерный массив из чисел от 1 до 10. Затем преобразуйте его в двумерный массив 2x5. Найдите сумму всех элементов массива, а также среднее арифметическое.

In [2]:
import numpy as np

In [3]:
# Место для вашего кода :)
arr = np.arange(1, 11)
arr2 = arr.reshape(2, 5)

sum = np.sum(arr2)
mean = np.mean(arr2)
print(f"Двумерный массив 2x5:")
print(arr2)
print(f"Сумма всех элементов массива: {sum}")
print(f"Среднее арифметическое элементов массива: {mean}")

Двумерный массив 2x5:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Сумма всех элементов массива: 55
Среднее арифметическое элементов массива: 5.5


##### 2. Создайте матрицу размером 5x5, содержащую числа от 1 до 25. Извлеките из неё:
1. Первый столбец
2. Последние три элемента второй строки
3. Центральный элемент массива

In [4]:
# Место для вашего кода :)
matrix = np.arange(1, 26).reshape(5, 5)
print(f'Матрица')
print(matrix)
print(f'Первый столбец {matrix[:, 0]}')
print(f'Последние 3 элемента второй строки {matrix[1, -3:]}')
print(f'Центральный элемент массива {matrix[2, 2]}')

Матрица
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Первый столбец [ 1  6 11 16 21]
Последние 3 элемента второй строки [ 8  9 10]
Центральный элемент массива 13


##### 3. Создайте массив из 20 случайных чисел. Найдите:
1. Минимальное и максимальное значения
2. Медиану
3. Стандартное отклонение

In [5]:
# Место для вашего кода :)
arr = np.random.randint(1, 101, 20)
print(f"Минимальное значение {arr.min()}, а максимальное {arr.max()}")
print(f"Медиана - {np.median(arr)}")
print(f"Стандартное отклоненение - {round(np.std(arr), 4)}")

Минимальное значение 2, а максимальное 97
Медиана - 60.0
Стандартное отклоненение - 29.6108


##### 4. Создайте массив случайных чисел от 0 до 100 (10 элементов). Определите, какие из них чётные. Замените все нечётные элементы на 0.

In [6]:
# Место для вашего кода :)
arr = np.random.randint(1, 101, 20)
print(arr)
for i in range(len(arr)):
    if (arr[i] % 2) != 0:
        arr[i] = 0
print(arr)

[72 96  2 85 43 95 36 66 38 22 14 26 72 30 92 37 81 47 71 57]
[72 96  2  0  0  0 36 66 38 22 14 26 72 30 92  0  0  0  0  0]


##### 5.1 Создайте матрицу произвольного размера. 
1. Найдите транспонированную матрицу.
2. Найдите обратную матрицу, если это возможно.
3. Найдите собственные значения и собственные вектора.

In [7]:
# Место для вашего кода :)
matrix = np.random.randint(0, 101,(np.random.randint(1, 11),np.random.randint(1, 11)))
print(matrix)
print("\nТранспонирвоанная матрица")
print(np.transpose(matrix))
if (matrix.shape[0] == matrix.shape[1]) and (np.linalg.det(matrix) != 0):
    print("\nОбратная матрица")
    print(np.linalg.inv(matrix))
else:
    print("\nМатрица вырождена")

if (matrix.shape[0] == matrix.shape[1]):
    print("Собственные значения:", np.linalg.eig(matrix)[0])
    print("Собственные векторы:\n", np.linalg.eig(matrix)[1])

[[ 11  74  49  11  85  24  62  65]
 [ 33  17  13  56  31   2  56  72]
 [ 33  72  91  63 100  28  42  65]
 [  9  13  80  42  64  45  53   6]
 [ 77   9  95  70  67  97  79   4]
 [ 72  45  35  13  20  38  24  25]
 [ 31   3  22  88  62  48  54  96]
 [ 29  60  97  59  68  37  81 100]
 [ 65  64  50  93  63   3  92  90]
 [ 99  71  31  77  59   7  31  90]]

Транспонирвоанная матрица
[[ 11  33  33   9  77  72  31  29  65  99]
 [ 74  17  72  13   9  45   3  60  64  71]
 [ 49  13  91  80  95  35  22  97  50  31]
 [ 11  56  63  42  70  13  88  59  93  77]
 [ 85  31 100  64  67  20  62  68  63  59]
 [ 24   2  28  45  97  38  48  37   3   7]
 [ 62  56  42  53  79  24  54  81  92  31]
 [ 65  72  65   6   4  25  96 100  90  90]]

Матрица вырождена


##### 5.2 Создайте две матрицы 4x4, заполненные случайными числами. Выполните следующие операции:

1. Найдите их матричное произведение.
2. Объедините две матрицы в тензор/в одну матрицу 4x8.

In [8]:
# Место для вашего кода :)
matrix = np.random.randint(0, 101,(4,4))
matrix2 = np.random.randint(0, 101,(4,4))
print("Матричное произведение:")
print(matrix @ matrix2)
print("Объединенная матрица:") #тензор через np.stack, но задание было или тензор или одну матрицу.
print(np.concatenate((matrix, matrix2), axis=1))

Матричное произведение:
[[ 9544  9243  1892 15969]
 [ 6230  5877  2710 12187]
 [ 9628  9131  3814 22468]
 [ 5308  6462  1820 11700]]
Объединенная матрица:
[[ 15  56  94  69  18  18  30  92]
 [ 58   9 100  17  68  14   0  90]
 [ 95  77  23  78  42  35   8  48]
 [ 32  31  30  62  22  71  10  73]]


##### 6. Создайте трёхмерный массив размером 3x3x3, заполненный случайными числами. Выполните следующие операции:
1. Найдите сумму элементов по каждой оси.
2. Найдите минимальный элемент для каждого слоя.
3. Отсортируйте каждый слой по возрастанию.

In [9]:
# Место для вашего кода :)
arr = np.random.random((3, 3, 3))
print(arr)
print("\nСумма по оси 0:\n", np.sum(arr, axis=0))
print("\nСумма по оси 1:\n", np.sum(arr, axis=1))
print("\nСумма по оси 2:\n", np.sum(arr, axis=2))

print("\nМинимальные элементы каждого слоя:\n", np.min(arr, axis=(1, 2)))

print("\nТрехмерный массив после сортировки:\n", np.sort(arr, axis=1))

[[[0.40226037 0.93431658 0.32085866]
  [0.05513061 0.5300141  0.78485729]
  [0.13440343 0.87613975 0.84921295]]

 [[0.63800002 0.10013521 0.22335308]
  [0.68543924 0.40076286 0.57488441]
  [0.94740218 0.53832427 0.6305423 ]]

 [[0.18410394 0.26825619 0.56012576]
  [0.46524927 0.46441529 0.29674994]
  [0.48011804 0.485176   0.89766592]]]

Сумма по оси 0:
 [[1.22436434 1.30270798 1.1043375 ]
 [1.20581912 1.39519225 1.65649164]
 [1.56192364 1.89964002 2.37742116]]

Сумма по оси 1:
 [[0.59179441 2.34047043 1.95492889]
 [2.27084143 1.03922233 1.42877979]
 [1.12947125 1.21784748 1.75454162]]

Сумма по оси 2:
 [[1.65743561 1.370002   1.85975612]
 [0.9614883  1.66108651 2.11626874]
 [1.0124859  1.2264145  1.86295996]]

Минимальные элементы каждого слоя:
 [0.05513061 0.10013521 0.18410394]

Трехмерный массив после сортировки:
 [[[0.05513061 0.5300141  0.32085866]
  [0.13440343 0.87613975 0.78485729]
  [0.40226037 0.93431658 0.84921295]]

 [[0.63800002 0.10013521 0.22335308]
  [0.68543924 0.4007

##### 7. Сгенерируйте набор данных из 100 случайных точек в 3D-пространстве. Выполните их нормализацию (приведите к единичному масштабу) по каждой оси.

In [10]:
# Место для вашего кода :)
arr = np.random.random((100, 3))
normal = (arr - arr.min(axis=0)) / (arr.max(axis=0) - arr.min(axis=0))
print(normal)


[[0.37516124 0.78608803 0.0106281 ]
 [0.65144259 0.00773697 0.72496243]
 [0.65889166 0.91159517 0.24646388]
 [0.14659596 0.14796707 0.53894293]
 [0.13225243 0.40882517 0.1637041 ]
 [0.23499925 0.24316264 0.44028811]
 [0.91536847 0.32850442 0.51535918]
 [1.         0.39144208 0.02412398]
 [0.15891072 0.48653399 0.96765332]
 [0.3838226  0.95639085 0.62273991]
 [0.6005401  0.79388388 0.64043367]
 [0.7277061  0.7534761  0.18381873]
 [0.01641756 0.29297812 0.20888897]
 [0.01486939 0.79857221 1.        ]
 [0.46955262 0.32421856 0.84422796]
 [0.1321534  0.12524742 0.9974656 ]
 [0.60511158 0.65733536 0.58670226]
 [0.49426102 0.39536444 0.43053786]
 [0.39289786 0.38097767 0.52230173]
 [0.89819118 0.30363336 0.53068138]
 [0.17246495 0.58355926 0.66969046]
 [0.24451462 0.50641592 0.77976295]
 [0.24823652 0.90398082 0.39164629]
 [0.26967844 0.84337992 0.56355871]
 [0.75915199 0.67674065 0.89830313]
 [0.17804447 0.60708855 0.28979571]
 [0.98017722 0.28289021 0.30390455]
 [0.53464102 0.87674758 0.64

##### 8*. Загрузите любое изображение (в рамках приличия, конечно) и сожмите его с помощью сингулярного разложения (SVD). Выберете разное количество сингулярных значений и сравните полученный результат с оригиналом.

In [ ]:
# Место для вашего кода :)